config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories
  resources :appointments
  resources :patients
  resources :doctors
  root to:  'pages#index'
end

app/views/pages/_header.html.erb
<style type="text/css">
  .buildcode{
    color: #33f0bc !important;
  }
</style>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'buidcode', '', class: 'navbar-brand buildcode' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
        <% if user_signed_in? %>
          <li class="nav-item" >
            <%= link_to 'Doctors', doctors_path, class: 'navbar-brand' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Patients', patients_path, class: 'navbar-brand' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Appointments', appointments_path, class: 'navbar-brand' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'navbar-brand' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-brand' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'navbar-brand' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'navbar-brand' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<br><br>

app/views/pages/index.html.erb
<h1 style="font-size: 20px;">Welcome, please choose from the options above </h1>