config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories
  resources :appointments
  resources :patients
  resources :doctors
  root to:  'pages#index'
end

app/models/patient.rb
class Patient < ApplicationRecord
	validates :name, :birth_date, :cpf, :presence => true
	validates :cpf, length: { is: 11 }, uniqueness: true
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:name, :birth_date, :cpf)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <% form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <div class="field form-group"> 
    <td>Date of birth</td>
    <% form.label :birth_date %>
    <%= form.date_select :birth_date, class:"form-control", placeholder:"Birth date" %>
  </div>

  <div class="field form-group">
    <% form.label :cpf %>
    <%= form.number_field :cpf, class:"form-control", placeholder:"CPF: xxxxxxxxxxx" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Birth date</th>
      <th>Cpf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.birth_date %></td>
        <td><%= patient.cpf %></td>
        <td><%= link_to 'Show', patient, class:'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient), class:'btn btn-primary' %></td>
        <td><%= button_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path, class:'btn btn-success' %>

app/views/patients/new.html.erb
<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Birth date:</strong>
  <%= @patient.birth_date %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @patient.cpf %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient), class:'btn btn-secondary' %> 
<%= link_to 'Back', patients_path, class:'btn btn-dark' %>