config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :stories
  resources :appointments
  resources :patients
  resources :doctors
  root to:  'pages#index'
end

app/models/doctor.rb
class Doctor < ApplicationRecord
	states = ["AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA",
			  "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "PJ", "RN",
			  "RS", "RO", "RR", "SC", "SP", "SE", "TO"]
	
	validates :name, :crm, :crm_uf, :presence => true
	validates :crm_uf, :inclusion => {:in => states, message: "%{value} is not a valid state. valid states: AC, AL, AP, AM, BA, CE, DF, ES, GO, MA, MT, MS, MG, PA, PB, PR, PE, PI, PJ, RN, RS, RO, RR, SC, SP, SE, TO"}
	validates :crm_uf, uniqueness: {scope: :crm}
	#validates :crm, uniqueness: {scope: :crm_uf}
	before_save :uppercase_crm_uf

	def uppercase_crm_uf
		crm_uf.upcase!
	end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /doctors or /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1 or /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors or /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: "Doctor was successfully created." }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1 or /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: "Doctor was successfully updated." }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1 or /doctors/1.json
  def destroy
    require 'sqlite3'

    begin
        
        db = SQLite3::Database.open "test.db"
        
        stm = db.prepare "SELECT doctor_id FROM appointments" 
        rs = stm.execute 
        
        rs.each do |row|
            puts row.join "\s"
        end
               
    rescue SQLite3::Exception => e 
        
        puts "Exception occurred"
        puts e
        
    ensure
        stm.close if stm
        db.close if db
    end
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def doctor_params
      params.require(:doctor).permit(:name, :crm, :crm_uf)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_form.html.erb
<%= form_with(model: doctor) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>
      <ul>
        <% doctor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class= "form-control">
  <div class="field">
    <% form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <div class="field form-group">
    <% form.label :crm %>
    <%= form.number_field :crm, class:"form-control", placeholder:"CRM" %>
  </div>

  <div class="field form-group">
    <% form.label :crm_uf %>
    <%= form.text_field :crm_uf, class:"form-control", placeholder:"UF" %>
  </div>

</div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/edit.html.erb
<%= render 'form', doctor: @doctor %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

app/views/doctors/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Crm</th>
      <th>Crm uf</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.crm %></td>
        <td><%= doctor.crm_uf %></td>
        <td><%= link_to 'Show', doctor, class:'btn btn-primary'%></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor), class:'btn btn-primary' %></td>
        <td>
          <% doctor.id %>
          <%= button_to 'Delete', doctor, class:'btn btn-danger', method: :delete, data: { action: "destroy" , confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path, class:'btn btn-success' %>

app/views/doctors/new.html.erb
<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Crm:</strong>
  <%= @doctor.crm %>
</p>

<p>
  <strong>Crm uf:</strong>
  <%= @doctor.crm_uf %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor), class:'btn btn-secondary' %> 
<%= link_to 'Back', doctors_path, class:'btn btn-dark' %>